apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uddhao1
spec:
  destination:
    name: zuscu-d006-b207-aks-d1-atldp
    namespace: uddhao
    server: ''
  source:
    path: dev
    repoURL: 'https://github.com/Uddhao/ArgoCD.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
