apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upbootstrap
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  project: default
  source:
    path: bootsrap/
    repoURL: https://github.com/Uddhao/ArgoCD
    directory:
      recurse: true
  syncPolicy:
    automated: {}
