apiVersion: v1
kind: Service
metadata:
  name: helloworldser
  namespace: cc-dev
spec:
  selector:
    app: helloworlddep
  ports:
    - name: http
      port: 8098
      targetPort: 80
  type: LoadBalancer
