apiVersion: v1
kind: Service
metadata:
  name: helloworldser
  namespace: default
spec:
  selector:
    app: helloworlddep
  ports:
    - name: http
      port: 8098
      targetPort: 80
  type: LoadBalancer
