apiVersion: v1
kind: Service
metadata:
  name: weatherapiser
  namespace: cc-dev
spec:
  selector:
    app: weatherapidep
  ports:
    - name: http
      port: 8098
      targetPort: 80
  type: LoadBalancer