apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  creationTimestamp: null
  name: upweatherapi
  namespace: uddhao
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - cluster: dp
        name: zuscu-d006-b207-aks-d1-atldp
  template:
    metadata:
      name: '{{.cluster}}-upweatherapi'
    spec:
      project: default
      source:
        repoURL: https://github.com/Uddhao/ArgoCD.git
        targetRevision: HEAD
        path: dev
      destination:
        server: {{.name}}
        namespace: uddhao
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
